import axios from 'axios'
import { useAuthStore } from '../store/authStore'

const api = axios.create({
  baseURL: '/api',
})

api.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token
  if (token) config.headers.Authorization = `Bearer ${token}`
  return config
})

export interface BalanceResult {
  accountId: string
  amount: number
}

export interface PaymentDto {
  id: string
  amount: number
  status: 'Pending' | 'Paid' | 'Overdue' | 'Cancelled' | 'Failed'
  type: string
  createdAt: string
  paidAt: string | null
}

export interface PayViaBalanceResult {
  success: boolean
  reason?: string
}

export interface CreatePaymentResult {
  id: string
}

export const authApi = {
  login: (licenseId: string) =>
    api
      .post<{ token: string; accountId: string; licenseId: string }>('/auth/login', { licenseId })
      .then((r) => r.data),
}

export const balanceApi = {
  getBalance: (accountId: string) =>
    api.get<BalanceResult>(`/balance/${accountId}`).then((r) => r.data),

  topUp: (accountId: string, amount: number) =>
    api.post<{ newBalance: number }>('/balance/topup', { accountId, amount }).then((r) => r.data),
}

export const paymentsApi = {
  getPayments: (licenseId: string) =>
    api.get<{ payments: PaymentDto[] }>(`/payments/${licenseId}`).then((r) => r.data.payments),

  /**
   * Pay via account balance. Requires an Idempotency-Key header.
   * Use `useIdempotentMutation` instead of calling this directly from React components.
   *
   * @param paymentId  The payment to settle
   * @param accountId  The balance account to debit
   * @param amount     Expected amount (validated server-side)
   * @param idempotencyKey  Stable UUID generated by useIdempotentMutation
   */
  payViaBalance: (
    paymentId: string,
    accountId: string,
    amount: number,
    idempotencyKey: string,
  ): Promise<PayViaBalanceResult> =>
    api
      .post<PayViaBalanceResult>(
        '/payments/pay-via-balance',
        { paymentId, accountId, amount },
        { headers: { 'Idempotency-Key': idempotencyKey } },
      )
      .then((r) => r.data),

  /**
   * Create a new payment intent. Requires an Idempotency-Key header.
   * Use `useIdempotentMutation` instead of calling this directly from React components.
   */
  createPayment: (
    payload: {
      licenseId: string
      amount: number
      type: string
      externalPaymentId?: string
      providerId?: string
      targetId?: string
    },
    idempotencyKey: string,
  ): Promise<CreatePaymentResult> =>
    api
      .post<CreatePaymentResult>('/payments/create', payload, {
        headers: { 'Idempotency-Key': idempotencyKey },
      })
      .then((r) => r.data),
}

async function retryOn409<T>(fn: () => Promise<T>, timeoutMs = 30_000): Promise<T> {
  const deadline = Date.now() + timeoutMs
  while (true) {
    try {
      return await fn()
    } catch (err: unknown) {
      if (
        typeof err === 'object' &&
        err !== null &&
        'response' in err &&
        (err as { response?: { status?: number } }).response?.status === 409
      ) {
        if (Date.now() >= deadline) throw err
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      throw err
    }
  }
}

export interface QuickPayResult {
  success: boolean
  reason?: string
  paymentId?: string
}

/**
 * Single-request generate-and-pay: server checks balance first.
 * If insufficient, creates a Failed payment record and returns the reason.
 * If sufficient, creates Pending then atomically pays it.
 */
export async function generateAndPay(
  licenseId: string,
  accountId: string,
  type: string,
  amount: number,
): Promise<QuickPayResult> {
  const idempotencyKey = crypto.randomUUID()
  return retryOn409(() =>
    api
      .post<QuickPayResult>(
        '/payments/quick-pay',
        { licenseId, accountId, type, amount },
        { headers: { 'Idempotency-Key': idempotencyKey } },
      )
      .then((r) => r.data)
      .catch((err: unknown) => {
        // 422 = insufficient balance — treat as a known result, not a thrown error
        const axiosErr = err as { response?: { data?: QuickPayResult; status?: number } }
        if (axiosErr?.response?.status === 422 && axiosErr.response.data) {
          return axiosErr.response.data
        }
        throw err
      }),
  )
}

export default api
