import axios from 'axios'
import { useAuthStore } from '../store/authStore'

const api = axios.create({
  baseURL: '/api',
})

api.interceptors.request.use((config) => {
  const token = useAuthStore.getState().token
  if (token) config.headers.Authorization = `Bearer ${token}`
  return config
})

export interface BalanceResult {
  accountId: string
  amount: number
}

export interface PaymentDto {
  id: string
  amount: number
  status: 'Pending' | 'Paid' | 'Overdue' | 'Cancelled'
  type: string
  createdAt: string
  paidAt: string | null
}

export interface PayViaBalanceResult {
  success: boolean
  reason?: string
}

export interface CreatePaymentResult {
  id: string
}

export const balanceApi = {
  getBalance: (accountId: string) =>
    api.get<BalanceResult>(`/balance/${accountId}`).then((r) => r.data),

  topUp: (accountId: string, amount: number) =>
    api.post<{ newBalance: number }>('/balance/topup', { accountId, amount }).then((r) => r.data),
}

export const paymentsApi = {
  getPayments: (licenseId: string) =>
    api.get<{ payments: PaymentDto[] }>(`/payments/${licenseId}`).then((r) => r.data.payments),

  /**
   * Pay via account balance. Requires an Idempotency-Key header.
   * Use `useIdempotentMutation` instead of calling this directly from React components.
   *
   * @param paymentId  The payment to settle
   * @param accountId  The balance account to debit
   * @param amount     Expected amount (validated server-side)
   * @param idempotencyKey  Stable UUID generated by useIdempotentMutation
   */
  payViaBalance: (
    paymentId: string,
    accountId: string,
    amount: number,
    idempotencyKey: string,
  ): Promise<PayViaBalanceResult> =>
    api
      .post<PayViaBalanceResult>(
        '/payments/pay-via-balance',
        { paymentId, accountId, amount },
        { headers: { 'Idempotency-Key': idempotencyKey } },
      )
      .then((r) => r.data),

  /**
   * Create a new payment intent. Requires an Idempotency-Key header.
   * Use `useIdempotentMutation` instead of calling this directly from React components.
   */
  createPayment: (
    payload: {
      licenseId: string
      amount: number
      type: string
      externalPaymentId?: string
      providerId?: string
      targetId?: string
    },
    idempotencyKey: string,
  ): Promise<CreatePaymentResult> =>
    api
      .post<CreatePaymentResult>('/payments/create', payload, {
        headers: { 'Idempotency-Key': idempotencyKey },
      })
      .then((r) => r.data),
}

export default api
